name: seo
description: Flutter package for enabling SEO (meta, body tag) support on Web.
version: 0.0.3
homepage: https://github.com/krokyze/flutter_seo

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  collection: ^1.16.0
